# Site settings
name: 清风向晚的博客
email: 1107322916@qq.com
author: XSJ
url: http://www.findfriend.xyz
resume_site: https://AndyofJuly.github.io
github: https://AndyofJuly.github.io
baseurl: ''
description: Actually, less is more!
meta_description: 谢少杰
motto: All I want is a simple life
banner: 只有珍惜往事的人才真正地生活

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: AndyofJuly

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

